### ISSUE TITLE
python api 无法加载 ControlUnit 动态库

### ISSUE THREAD

**Issue by where2go947** [MaaAssistantArknights/MaaFramework#108]
大佬您好，我在尝试看您`sample/python`下的代码，遇到了一些问题，如果您有空的话，可以解答一下吗：
1. 自己尝试时，这里在建立连接报错：`RuntimeError: Failed to create ADB controller`（实际端口port是从`bluestacks.conf`中读取的，且检查过没问题）
https://github.com/MaaAssistantArknights/MaaFramework/blob/5cd4cc945e395edfca47a7b4096b1885fcb807da/sample/python/__main__.py#L14
2. debug发现，似乎是`self._handle`为空：
https://github.com/MaaAssistantArknights/MaaFramework/blob/5cd4cc945e395edfca47a7b4096b1885fcb807da/source/binding/Python/maa/controller.py#L313-L324
3.而在`library.py`中，确实没有看到函数`Library.framework.MaaAdbControllerCreateV2`的定义。`Library.framework`是类型`WinDLL : ...`， `Library`应该是正常加载了（`Library.open(...)`），请问是我哪里理解错了吗

目前是想先用python和Bluestacks 5建立连接，再去看流程怎么搭建，windows 10平台。然而卡在连接上了，希望大佬能看一下，谢谢！

**Comment by MistEO** [comment]
发下 debug 文件夹看看，里面有日志

**Comment by MistEO** [comment]
> 而在library.py中，确实没有看到函数Library.framework.MaaAdbControllerCreateV2的定义

这个 MaaAdbControllerCreateV2 是是动态库里的函数

**Comment by MistEO** [comment]
看起来是 1.3.0 版本引入了 bug，python api 不能正常运行了，你可以等等先试试 1.2.0 + python api，或者 1.3.0 + c api

**Comment by where2go947** [comment]
好的，谢谢~

**Comment by MistEO** [comment]
Windows修了，linux下的不会弄，等个有缘的大佬

**Comment by MistEO** [comment]
https://blog.csdn.net/buknow/article/details/89407519
https://www.cnblogs.com/lidabo/p/17078906.html

找了点参考资料，mark，之后修下

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaFramework/commit/d01da10a51110879a7bf7bb4e54ff9c487a1a774 fixed
