### ISSUE TITLE
[Feature Request] 希望加入输入/粘贴文本功能

### ISSUE THREAD

**Issue by FSPaul2498** [MaaAssistantArknights/MaaFramework#114]
如题，现有一个app的自动化测试场景，每个单词为一个case，需要将词语填入app中的某个文本框再执行测试，希望能够加入这方面的功能，可以在app中直接输入/粘贴指定的文本（以参数或其他形式传入）

**Comment by MistEO** [comment]
已支持 ControllerAPI / SyncContextAPI / Pipeline / Proto RPC / ExecAgent 全部功能的文本输入
