### ISSUE TITLE
想要問問萌新如何參與這個項目

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/MaaFramework#14]
純開發方面是個新手 有什麼可以做的?

另外這個項目未來會有什麼low code的開發方式嗎，例如

- 簡單的gui介面
- 簡單的圖像辨識
- 簡單的連接裝置

**Comment by MistEO** [comment]
之后会有类似主仓库 tasks.json 那种 DSL 可以弄，敬请期待~

**Comment by TeemoKill** [comment]
我在这里睡一个觉，有了请戳我

**Comment by MistEO** [comment]
有了：[文档](https://github.com/MaaAssistantArknights/MaaFramework/blob/main/docs/zh_cn/3.3-%E4%BB%BB%E5%8A%A1%E6%B5%81%E6%B0%B4%E7%BA%BF%E5%8D%8F%E8%AE%AE.md)

一个简单的 demo：[重返未来 1999 启动游戏流程](https://github.com/MaaAssistantArknights/MAA1999/blob/main/assets/resource/pipeline/startup.json)
