### ISSUE TITLE
[Enhancement] 让流水线能够从子任务中结束

### ISSUE THREAD

**Issue by moomiji** [MaaAssistantArknights/MaaFramework#22]
子任务需要一个 `is_done` 属性字段，让流水线直接结束。

`is_done` 默认值如下：
```
if is_sub == true:
    is_done = false;

if is_sub == false:
    is_done = true;
```

例如以下任务需要 `is_done`：
```mermaid
graph TD;
    任务-->正常运行-->完成;
    任务-->Sub_遇到游戏报错;
    Sub_遇到游戏报错-->Warning_继续运行-->任务;
    Sub_遇到游戏报错-->Done_Error-->notify-->完成;
```

适用于待测软件经常报错且错误类型多种多样，能够将报错检测或某一类任务整合起来。

目前版本是这样处理报错的，需要将每个 Warning 和 Error 的检测任务添加到 next 字段:
```mermaid
graph TD;
    任务-->正常运行-->完成;
    任务-->Sub_Warning1-->任务;
    任务-->Sub_Warning234-->任务;
    任务-->Error1-->notify;
    任务-->Error234-->notify;
    notify-->完成;
```

**Comment by MistEO** [comment]
好像可以加个 Action "Stop"，怎么样

**Comment by moomiji** [comment]
fw怎么方便怎么来




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月31日(周一) 凌晨0:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaFramework] [Enhancement] 让流水线能够从子任务中结束 (Issue #22)




 
好像可以加个 Action "Stop"，怎么样
