### ISSUE TITLE
TemplateMatch 匹配圖片得分偏低

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/MaaFramework#25]
模擬器解析度 : 720 x 1280
圖片使用的是BS5自帶的截圖功能

參考圖片 : [原圖.zip](https://github.com/MaaAssistantArknights/MaaFramework/files/12237011/default.zip)

前端用的是nekosu寫的MaaCommonJS
寫了一個training.json去執行
MaaFW目前使用的是fix: vcxproj #526 版本

預期設計 :
1. 在大廳點擊Tap的按鈕收取資源
2. 點X回到大廳

目前問題 :
使用新的CropRoi工具裁切出了Tap.png 跟 tapexit.png 兩張圖
但是使用TemplateMatch 的方式，得分都會偏低，只有0.2~0.3，無法判別

log請參考
[log.zip](https://github.com/MaaAssistantArknights/MaaFramework/files/12237029/log.zip)

**Comment by MistEO** [comment]
你写的json和你裁出来的图也发一下

**Comment by Arcelibs** [comment]
寫的Json
[training.zip](https://github.com/MaaAssistantArknights/MaaFramework/files/12237219/training.zip)

截的圖
[Training.zip](https://github.com/MaaAssistantArknights/MaaFramework/files/12237220/Training.zip)

**Comment by MistEO** [comment]
你的宽度是 720，这 ROI 都到外面去了啊

![image](https://github.com/MaaAssistantArknights/MaaFramework/assets/18511905/ea50d822-3f8d-4610-909b-fec92d7212e0)

**Comment by Arcelibs** [comment]
今天再試，ocr辨識後不會點擊

圖片↓
[Vision.zip](https://github.com/MaaAssistantArknights/MaaFramework/files/12249167/Vision.zip)

log
[maa_log.zip](https://github.com/MaaAssistantArknights/MaaFramework/files/12249173/maa_log.zip)

現在的json
[training.zip](https://github.com/MaaAssistantArknights/MaaFramework/files/12249179/training.zip)

**Comment by Arcelibs** [comment]
改了一下，第一步直接使用TemplateMatch，不填roi
得出來的是這樣，但是一樣action click沒有動作

![Tap_2023 08 03-17 31 55 5373803](https://github.com/MaaAssistantArknights/MaaFramework/assets/49543451/3b2c3109-04d5-4b9f-88ce-9721c527fa90)

**Comment by Arcelibs** [comment]
新的log跟截圖
[debug.zip](https://github.com/MaaAssistantArknights/MaaFramework/files/12250037/debug.zip)

**Comment by Arcelibs** [comment]
使用了新版本的maaFW後能夠成功識別了，謝謝瑪麗

[debug.zip](https://github.com/MaaAssistantArknights/MaaFramework/files/12262618/debug.zip)
