### ISSUE TITLE
MaaFW功能詢問!

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/MaaFramework#29]
MaaFW功能詢問!

有這樣的功能嗎
指定區域內 不含有a.png 跟 b.png的選項 隨機挑選他
 
範例 : 
我想要選擇區域內，亮著的人
![image](https://github.com/MaaAssistantArknights/MaaFramework/assets/49543451/1b82b54a-588a-41b9-91de-89a01c1545cd)

於是我的判斷想要設計成，不去選上面有「仕事中」跟「元氣最大」的人
或者循序點擊每張圖，點滿三個人就好(但是有灰底這要怎麼判斷?)

還是瑪麗有什麼推薦的設計作法?

**Comment by MistEO** [comment]
识别搞个 "reverse" 字段怎么样，识别到了反而是认为没匹配上
