### ISSUE TITLE
[Feature Request] 双指缩放/放大

### ISSUE THREAD

**Issue by moomiji** [MaaAssistantArknights/MaaFramework#38]

**Comment by neko-para** [comment]
我感觉要做的话得改TouchInput的抽象, 至少得把swipe拆成独立的down和up.
其实可以直接参考minitouch, 然后对于AdbTouchInput做个batch来模拟(但是好像adb input确实做不了缩放

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaFramework/commit/2eb0ce40675c99408d29a91bac471311c349c39b

接口给你了，剩下的看着办吧.jpg
