### ISSUE TITLE
[TODO] 文档

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaFramework#47]

**Comment by zkcrescent** [comment]
想要上手自己试验一把该工具，但是发现没什么文档，急切需要一个可以类似于startup的文档来快速上手

**Comment by MistEO** [comment]
> 想要上手自己试验一把该工具，但是发现没什么文档，急切需要一个可以类似于startup的文档来快速上手

可以参考 sample（确信
