### ISSUE TITLE
[Feature request] 需要一个字段用来指示任务链运行到终点时，是否失败

### ISSUE THREAD

**Issue by moomiji** [MaaAssistantArknights/MaaFramework#51]
当前返回 MaaStatus_Failed 的貌似只有任务超时

**Comment by MistEO** [comment]
除了超时还有啥叫失败（

**Comment by moomiji** [comment]
自定义失败（
比如启动游戏，可能会由于网络原因一直找不到出口然后一直尝试 Sub_StartApp（MAA1999 启动漏洞
所以 Sub_StartApp 会使用 runout_next
runout_next 必接着 StopTask
这里 StopTask 返回的是成功，而不是预期的失败

**Comment by MistEO** [comment]
StopTask 只是一个普通的 action，我觉得他就应该返回 true

或许可以通过 GetTaskResult 接口来返回一下具体执行了哪些任务，然后调用方自己判断下？

**Comment by moomiji** [comment]
那 focus 也可以做到吧，但这样的话 fw 的返回结果就不可信了（

**Comment by moomiji** [comment]
或者我们需要给 MaaStatus 下个精确点的定义

MaaStatus_Failed 如果是指示 fw 的工作状态失败，而不是任务失败，返回 true 就没问题

**Comment by MistEO** [comment]
或者给 json 里每个加一个返回值字段？

**Comment by moomiji** [comment]
GetTaskResult 获取任务结果，预定义为int ret = 0
 json 里加个返回值 value 预定义为 0
然后每经过一个任务按位或 ret = ret | value
这样 value 的定义交给调用方，一个 ret 就可以得到多个信息（

**Comment by MistEO** [comment]
摆烂了，推荐用 focus （

**Comment by moomiji** [comment]
到时我把 enum 包在 focus 上（
