### ISSUE TITLE
[TODO] 乱七八糟的整理

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaFramework#65]
- 产物包添加 binding
- 产物包添加 sample
- cmake 为 RPC CLI / test 添加选项
- 单独的冒烟及各种测试

**Comment by neko-para** [comment]
binding和sample要不还是分包吧, 但是分包的话再和arch一乘又多12个

**Comment by neko-para** [comment]
其实要说的话RPC CLI也应该分的
