### ISSUE TITLE
[Problem] 文档为空

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaFramework#77]
[2.1-回调协议.md](../blob/main/docs/zh_cn/2.1-%E5%9B%9E%E8%B0%83%E5%8D%8F%E8%AE%AE.md)
文档没有内容

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaFramework/blob/main/docs/zh_cn/2.2-%E5%9B%9E%E8%B0%83%E5%8D%8F%E8%AE%AE.md fixed
