### ISSUE TITLE
[Bug] Maa Touch read info timeout

### ISSUE THREAD

**Issue by dongwlin** [MaaAssistantArknights/MaaFramework#98]
![32be27eaa73a2134ab172ad94d7f665a](https://github.com/MaaAssistantArknights/MaaFramework/assets/97545700/987a951a-e442-45a5-907a-92985973b40e)
[maa.log](https://github.com/MaaAssistantArknights/MaaFramework/files/13309451/maa.log)
不懂捏

**Comment by MistEO** [comment]
不懂捏 @neko-para

**Comment by dongwlin** [comment]
![image](https://github.com/MaaAssistantArknights/MaaFramework/assets/97545700/a5529671-da1f-4af6-bdc0-1465c09e2192)

**Comment by MistEO** [comment]
重构完了，应该修了（确信
